name: e2e

on:
  pull_request:
  push:
    branches:
      - main
      - chore/**
      - feat/**
      - test/**
      - ci/**

jobs:
  e2e:
    name: Build and run Cypress E2E (preview on 3200)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Cypress run against preview
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          wait-on: 'http://localhost:3200'
          browser: chrome

      - name: Upload Cypress artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          if-no-files-found: ignore
          path: |
            cypress/screenshots
            cypress/videos
            cypress/logs

